Repository ryzen-stack/demo, pull requests merged in 2024-06, with the labels that each got.

#1 added index.html by vinay
  index.html
Labels: bug

#6 css file added
  home.css
Labels: duplicate

#8 created index.js
  index.js
Labels: documentation

#10 added to background colord
  home.css
Labels: documentation
